@startuml canary_release_03

!pragma teoz true
hide stereotype
skinparam dpi 300
skinparam linetype ortho
skinparam defaultFontSize 10
skinparam shadowing false
skinparam backgroundColor transparent

skinparam defaultFontName        "Verdana"
skinparam ParticipantPadding     10
skinparam BoxPadding             10
skinparam Padding                1

skinparam nodesep 5
skinparam ranksep 5

skinparam RoundCorner 10
skinparam ArrowColor #9DADC1
skinparam ArrowThickness 2
skinParam ArrowFontSize 5

skinparam defaultTextAlignment right

skinparam rectangle<<Default>> {
  BackgroundColor #F5F5F5

  BorderColor #E8E8E8
  BorderThickness 1

  FontColor #B3B3B3
  FontSize 7
  FontStyle bold
}

skinparam rectangle<<Red>> {
  BackgroundColor #FFD1C7

  BorderColor #FF7F60
  BorderThickness 1


  FontColor #FF7F60
  FontSize 7
  FontStyle bold
}

skinparam rectangle<<Blue>> {
  BackgroundColor #B3D8FF

  BorderColor #8CC4FF
  BorderThickness 1

  FontColor #77A7D9
  FontSize 7
  FontStyle bold
}

skinparam rectangle<<Green>> {
  BackgroundColor #B3FFEA
  
  BorderColor #4BEBBE
  BorderThickness 1

  FontColor #00b894
  FontSize 7
  FontStyle bold
}

rectangle "Padrões do Kubernetes" <<Default>> {
  rectangle "Princípios de Microserviços" <<Blue>> {
    rectangle "Projeto Orientado a Domínio" <<Green>> {
      rectangle "Código Limpo" <<Red>>
    }
  }
}

@enduml