@startuml kernel-stack

skinparam dpi 150

interface "SCI" as SCI

package "User Space" {
  component "Aplicação" as Application
  component "Biblioteca GNU C" as GLIBC
}

package "Kernel Space" {
  component "Kernel" as Kernel
}

package "Hardware" {
  component "Rede" as Network
  component "Storage" as Storage
  component "RAM" as RAM
  component "CPU" as CPU
}

Application -down-> GLIBC
GLIBC -right-> SCI
SCI -right- Kernel
Kernel --> CPU
CPU --> RAM
CPU --> Storage
CPU --> Network


@enduml
