== O Que veremos

ifndef::backend-revealjs[]
Sempre quis falar sobre containers, porém, nunca havia encontrado uma abordagem interessante ao assunto, visto a quantidade infinita de conteúdo sobre este assunto na internet. Com este contexto, decidi não falar sobre `Docker` especificamente, mas sim sobre todas as tecnologias que o tornou possível e além disso, a partir da disseminação de tecnologias relacionadas a containers, ilustrar como sua existência mudou completamente a industria de infraestrutura e desenvolvimento de software.

Não é objetivo deste documento ser a "fonte da verdade" sobre conteinerização ou sobre `Docker`, mas sim um compilado de informações sobre o assunto que compilei com o tempo. Por diversas vezes, utilizarei de uma linguagem despojada e despretensiosa e sempre que possível atribuirei fontes sobre o assunto. Vou te ajudar amigo ansioso.

Caso encontre algum problema, abra uma link:https://github.com/fabioluciano/containers-for-anxious-people/issues[issue] na página do projeto no GitHub.

Para seguir uma linha de raciocínio, escolhi dividir os assuntos abordados em seis partes. São elas:
endif::[]

ifdef::backend-revealjs[* Open Source;]
ifndef::backend-revealjs[=== Open Source]
ifndef::backend-revealjs[]
Na _primeira_ parte deste documento, conversaremos sobre *Open Source*. Discutiremos sobre as aplicações do movimento por diversos setores da indústria(até o alimentício 😲). Falarei sobre as principais licenças que caracterizam projetos do movimento livre, e também sobre os modelos implementados para organização destes projetos, falaremos sobre tipos de distribuições, como exemplo das possibilidades da implementação do `código-livre`, passearemos sobre grandes projetos, e por final, lhe farei um convite.
endif::[]

ifdef::backend-revealjs[* Sistemas Operacionais e sua arquitetura;]
ifndef::backend-revealjs[=== Sistemas Operacionais e sua arquitetura]
ifndef::backend-revealjs[]
Nesta _segunda_ parte , elucidarei como os sistemas operacionais evoluíram o suficiente para possibilitar tecnologias de virtualização disponíveis atualmente. Além disso, apresenta o `Kernel` do Linux de forma a introduzir conceitos utilizados por grande maioria dos provedores desta tecnologia.
endif::[]

ifdef::backend-revealjs[* Conteinerização;]
ifndef::backend-revealjs[=== Conteinerização]
ifndef::backend-revealjs[]
Na _terceira_ parte, vamos andar pelos caminhos mais íntimos da containerização. Observaremos como os conceitos há muito utilizados pelo Kernel do linux foram utilizado para criar soluções incríveis
endif::[]

ifdef::backend-revealjs[* Conversational Development;]
ifndef::backend-revealjs[=== Conversational Development]
ifndef::backend-revealjs[]
Na _quarta_ parte deste documento, 
endif::[]

ifdef::backend-revealjs[* (Dev(Sec)?|Chat)Ops;]
ifndef::backend-revealjs[=== (Dev(Sec)?|Chat)Ops]
ifndef::backend-revealjs[]
Na _quinta_ parte deste documento, 
endif::[]

ifdef::backend-revealjs[* Arquitetura de Software;]
ifndef::backend-revealjs[=== Arquitetura de Software]
ifndef::backend-revealjs[]
Na _sexta_ parte deste documento,
endif::[]

ifdef::backend-revealjs[* Arquitetura de Soluções;]
ifndef::backend-revealjs[=== Arquitetura de Soluções]
ifndef::backend-revealjs[]
Na _sétima_ e última parte deste documento,
endif::[]
