== Introdução

ifndef::backend-revealjs[]
Sempre quis falar sobre containers, porém, nunca havia encontrado uma abordagem interessante ao assunto, visto a quantidade infinita de conteúdo sobre este assunto na internet. Com este contexto, decidi não falar sobre `Docker` especificamente, mas sim sobre todas as tecnologias que o tornou possível.
Não é objetivo deste documento ser a "fonte da verdade" sobre containerização ou sobre `Docker`, mas sim um compilado de informações sobre o assunto.
Caso encontre algum problema, abra uma `issue` na página do projeto no GitHub.

Entre os assuntos abordados neste documento estão:
endif::[]

[.custom-style]
[cols="50a,50a"]
|===
|* Sistemas Operacionais e sua arquitetura;
* Conteinerização;
* DevOps;
* Arquitetura de Software;
| * Arquitetura de Soluções;
** Alta Disponibilidade;
** Clusterização;
** Construção de soluções tolerantes a falha;
** Cloud Computing;
|===


=== Sobre a distribuição deste documento
* link:/container-presentation/index.html[HTML]
* link:/container-presentation/documentation.pdf[Documento PDF]
* link:/container-presentation/presentation.html[Apresentação]
